import { Heading, Stack, Text } from "@chakra-ui/react";
import Head from "next/head";
import { AppShell } from "@/components/AppShell";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell>
        <Stack gap="4">
          <Heading as="h2" size="xl">
            Main
          </Heading>
          {Array.from({ length: 40 }, (_, i) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: static demo content
            <Text key={i}>スクロール確認用のダミーテキスト {i + 1}</Text>
          ))}
        </Stack>
      </AppShell>
    </>
  );
}
